\v
TITLE="New Developments Described At DLF Fall 2002 Forum in Seattle"
AUTHOR=""
PUBLISHER=""
EISBN=""
COPYRIGHT=""
\v\X0\bNew Developments Described At DLF Fall 2002 Forum in Seattle \b\X0

In the opening general session of the recent Digital Library Federation Forum in Seattle, \bBill Hill of Microsoft Research\b declared the impending end of one of the last obstacles to the triumph of electronic over printed information: print's superior readability.

Development of the electronic distribution of information is "the biggest revolution since Gutenberg," Hill said. "Printed information is out of date." Electronic distribution is more efficient. It costs less. Digital products can easily be searched, reproduced, and archived in small space, and you don't have to "clear-cut forests to communicate." Computerized devices that are getting smaller, lighter, faster, and cheaper are making libraries of digitized books available at any time, anywhere, in any language. "Tomorrow it's all digital," he said, because now a solution is at hand to the obstacle that people do not like to read extensive texts on computer screens.

Microsoft, he announced at the Forum's beginning on November 4, is launching the \bTabletPC\b, "the first personal computer designed as a reading surface," the culmination of "major efforts" to make "onscreen reading more like reading paper." The ordinary book, he explained, has "a simple user interface" with "no distractions from content." It is "bound to the human psyche," using "capabilities developed for survival." Man is "a visual pattern maker" who has "built writing systems" on "visual pattern matching," which is "unceasing and automatic." Now, Hill declared, "optimized serial pattern recognition" and "clear type technologies" are making it possible to "create a great reading experience on screen."

The 129 participants in the Forum, which the Digital Library Federation organizes semiannually, also heard from a colleague of Hill's at Microsoft Research, \bCathy Marshall\b, about "experiences with e-books in education." She reported on research confirming that students print out a lot because of the difficulty of on-screen reading, but she found that students increasingly read newspapers on screen and are likely to read e-books when these become more "book-like," and when e-libraries become available. For e-book development, easy mobility is important, as is navigation "among para-textual elements." Questions remain about how much annotation to make possible in e-books and how much of the "materiality of the page" to retain, such as the layout of lines of poetry. Marshall discussed doubts, however, about how much "in-depth reading" students do in any format: "cultural conditions for deep reading" seem to be "disappearing."

Participants at the Forum heard reports about other user studies as well.\b Denise Troll Covey\b of Carnegie Mellon University chaired a pre-Forum "e-metrics meeting," in which librarians compared experiences in their efforts to provide new statistical measurements of electronic resource development and use for reports regularly issued by the Association of Research Libraries. Then, in a regular session, Troll Covey reported on studies of difficulties experienced by users in getting remote access to library resources. The difficulties seem "exacerbated by the gap between the way commercial vendors restrict access to library resources and the way users access those resources."

Efforts to overcome such problems--how to "ensure the incorporation of digital library resources and services in virtual learning environments"--were described in a presentation by \bOya Rieger\b of Cornell. The discovery that only 12 percent of Web sites studied at that university contained any mention of its library led to creation of a Unified Service Working Group, through which campus librarians, information technologists, and specialists in media services and continuing education collaborate to provide faculty with a range of course-support services, all conveniently available through "one-stop shopping." Rieger recommended that librarians "take the library to the students," recognize the "strategic importance of Web sites," partner with academic technology centers "to develop integration strategies," participate when institutions "choose systems," and "help faculty select resources and develop tools."

As teachers and scholars create their own digital resources, some campus libraries attempt to "capture" and provide broader access to them. A panel chaired by\b Bob Wolven\b of Columbia University provided demonstrations and a discussion of "persistent issues that continue to confront these efforts"--issues of rights management, technical integration, sustainability, and use promotion. \bThornton Staples\b of the University of Virginia reported on questions that have arisen in a project there to collect digital scholarly projects into a digital library. "We're building big networks of information that are interrelated," he said, "not like books on shelves."

Speakers at the Forum also reported advances in developing services to "harvest" digital collections and information about them across the Internet, using the \bOpen Archives Initiative\b Protocol for Metadata Harvesting. Five institutions described their findings from work in a Metadata Harvesting Initiative funded by The Andrew W. Mellon Foundation. Emory University is at mid-point in its MetaScholar Project to create "metadata aggregation networks" on which specialized "subject portals" can be built. The Research Libraries Group is collecting MARC records in a Web-accessible Union Catalog aimed primarily at undergraduate use; prototypes are planned for next spring. The University of Michigan's OAIster Project is testing a search service drawing from 940,000 records covering a range of scholarly materials in 112 institutions. The University of Virginia is developing infrastructure including a "metadata workbench" for sorting out from "huge amounts of data" what will be useful to its American Studies Information Community. And an OAI Metadata Harvesting Project at the University of Illinois is building a high-volume search service focused on cultural heritage materials from multiple institutions. In a separate session, \bCaroline Arms\b reported on progress in implementing the OAI Protocol at the Library of Congress using content from its "American Memory" digital collection.

The presentations included requests for additional libraries to provide data for harvesting services--and a discussion of the difficulties in doing so. These arise more in creating high-quality metadata than in exposing it for harvesting.

The Forum also included reports on work at the University of Indiana to improve access to \bdigital music collections\b, including integrating sound records with images of musical scores; work at Cornell University on its \bDigital Publishing System\b for use in Project Euclid to foster scholarly publishing in mathematics and statistics; and work by the California Digital Library to develop, along with other products and services, its relatively new \beScholarship Repository\b to expand access to pre-publication scholarly products.

Several sessions at the Forum dealt with technical requirements for digital library development and resource sharing. Fred Beshears of the University of California discussed interoperability standards. Three participants in the \bShibboleth \bMiddleware Initiative discussed authentication mechanisms. John Walsh of Indiana University discussed the use of \bUnicode\b in projects to digitize foreign language material. A panel of implementers of the Metadata Encoding and Transmission Standard (\bMETS\b) described their progress, as did participants in a session on uses of the Metadata Object Description Schema (\bMODS\b). And Taylor Surface of OCLC discussed draft guidelines for its\b Digital Registry.
\b
In two sessions, the Forum also concerned itself with the major question of how digital libraries will preserve the scholarly resources they are creating, aggregating, and sharing. Abby Smith of the Council on Library and Information Resources reported on the now-completed planning phase of the \bNational Digital Information Infrastructure and Preservation Program\b, led, with Congressional funding, by the Library of Congress. And Michele Kimpton of the Internet Archives reported on efforts to "collaborate with national libraries to archive the Web."

In addition, the Forum included "\bBirds of a Feather\b" roundtables for open discussion of five subjects on which many DLF members are working: METS implementation; intellectual property rights agreements in digital projects; development of humanities computing centers in libraries; ways of dealing with multilingual digital library data; and creation of electronic publishing programs in libraries.

In mid-Forum, however, a special speaker interjected a cautionary note about all this activity by asking participants to consider "the dark edge of information technology." \bDavid Levy\b of the University of Washington's Information School argued that already society is "bogged down in more information than we can deal with." Information overload, he said, along with the rushing, busyness, and fragmentation of our lives, may be putting "life out of balance." This ubiquity of information, by reducing attention to what is most important, may even be "morally dangerous." He asked, "What if we begin to think about digital library work from the perspective of the need for silence and sanctuary and balance?" As "a symbol of organization and order," the library, he said, can help maintain the balance that our society needs.

\bDavid Seaman\b, the DLF's new director, opened the Forum by expressing his desire to improve communication within the DLF, involve more of the junior staffers of DLF institutions, and preserve the organization's ability to meet needs quickly. At the Forum's conclusion, he praised the liveliness of its informal as well as formal discussions and challenged participants "to promote DLF activities within your organizations," and "to share the information and insights the Forum has given you." 

\iJ.GEORGE, 11/26/02\i