{

document.write('<ol class="newsbold">')

document.write('<li><a href="http://www.bibalex.org/">Bibliotheca Alexandrina</a><br /></li><li>')

document.write('<a href="http://www.bl.uk/">British Library</a><br /></li><li>')
document.write('<a href="http://www.cdlib.org/">California Digital Library</a><br /></li><li>')
document.write('<a href="http://www.library.cmu.edu/">Carnegie Mellon University</a><br /></li><li>')
document.write('<a href="http://www.columbia.edu/cu/libraries/digital/">Columbia University</a><br /></li><li>')
document.write('<a href="http://campusgw.library.cornell.edu/">Cornell University</a><br /></li><li>')
document.write('<a href="http://www.clir.org/">Council on Library and Information Resources</a><br /></li><li>')
document.write('<a href="http://library.dartmouth.edu/">Dartmouth College</a><br /></li><li>')
document.write('<a href="http://www.emory.edu/LIBRARIES/">Emory University</a><br /></li><li>')
document.write('<a href="http://hul.harvard.edu/ldi/">Harvard University</a><br /></li><li>')
document.write('<a href="http://www.dlib.indiana.edu/">Indiana University</a><br /></li><li>')
document.write('<a href="http://webapps.jhu.edu/jhuniverse/libraries/">Johns Hopkins University</a><br /></li><li>')
document.write('<a href="http://www.digitalpreservation.gov">Library of Congress</a><br /></li><li>')
document.write('<a href="http://libraries.mit.edu/">Massachusetts Institute of Technology</a><br /></li><li>')
document.write('<a href="http://digital.nypl.org/">New York Public Library</a><br /></li><li>')
document.write('<a href="http://www.nyu.edu/library/">New York University</a><br /></li><li>')
document.write('<a href="http://www.lib.ncsu.edu/">North Carolina State University</a><br /></li><li>')
document.write('<a href="http://www.ouls.ox.ac.uk/">Oxford University</a><br /></li><li>')
document.write('<a href="http://www.libraries.psu.edu/">Pennsylvania State University</a><br /></li><li>')
document.write('<a href="http://libweb.princeton.edu/">Princeton University</a><br /></li><li>')
document.write('<a href="http://www.rice.edu/fondren/">Rice University</a><br /></li><li>')
document.write('<a href="http://www-sul.stanford.edu/">Stanford University</a><br /></li><li>')
document.write('<a href="http://sunsite.berkeley.edu/">University of California, Berkeley</a><br /></li><li>')
document.write('<a href="http://www2.library.ucla.edu/">University of California, Los Angeles</a><br /></li><li>')
document.write('<a href="http://www.lib.uchicago.edu/e/index.html">University of Chicago</a><br /></li><li>')
document.write('<a href="http://gateway.library.uiuc.edu/index.html">University of Illinois at Urbana-Champaign</a><br /></li><li>')
document.write('<a href="http://www.lib.umich.edu/lit/">University of Michigan</a><br /></li><li>')
document.write('<a href="http://www.lib.umn.edu/">University of Minnesota</a><br /></li><li>')
document.write('<a href="http://www.library.upenn.edu/">University of Pennsylvania</a><br /></li><li>')
document.write('<a href="http://www.usc.edu/libraries/">University of Southern California</a><br /></li><li>')
document.write('<a href="http://diglib.lib.utk.edu/dlc/">University of Tennessee</a><br /></li><li>')
document.write('<a href="http://www.lib.utexas.edu/">University of Texas at Austin</a><br /></li><li>')
document.write('<a href="http://www.lib.virginia.edu/">University of Virginia</a><br /></li><li>')
document.write('<a href="http://www.lib.washington.edu/">University of Washington</a><br /></li><li>')
document.write('<a href="http://www.archives.gov/index.html">U.S. National Archives and Records Administration</a><br /></li><li>')
document.write('<a href="http://www.nlm.nih.gov/">U.S. National Library of Medicine</a><br /></li><li>')
document.write('<a href="http://www.library.yale.edu/">Yale University</a></li>')
document.write('</ol>')

}
